### PR TITLE
Fix updates route

### LINKED ISSUE #105: Update Popup leads to Mozilla
When the browser is out of date, the popup that is shown leads to Mozilla's nightly page.

### LINKED ISSUE #107: Updates are borked
So, auto update does not work at all. Here is why.

1. The update url is wrong, it should be: `https://updates.pulsebrowser.app/browser/browser/%BUILD_TARGET%/%CHANNEL%/update.xml`
2. The generated hash is `[object Promise]` rather than the correct hash
3. The internationalization of the update string was broken by #88

### PR DESCRIPTION
**Pull request by PressJump**
Fixes #105 - Fixes #107

### CODE REVIEW

File: src/browser/app/profile/pulse-browser.js [hunk 1]
```diff
@@ -45,5 +45,10 @@ pref('dom.webmidi.enabled', true);
 pref("extensions.systemAddon.update.url", "https://updates.pulsebrowser.app/browser/addons/%CHANNEL%/update.xml");
 pref("extensions.systemAddon.update.enabled", true);
 
+//Update Routes (Download page for manual download and Temperoraliy Discord Invite Link for Release Notes)
+pref("app.update.url.manual", "https://pulsebrowser.app/download");
+pref("app.update.url.details", "hhttps://pulsebrowser.app/download");
+pref("app.releaseNotesURL", "https://discord.gg/Y3khyEtAgS");
```
Comment (trickypr) [inline src/browser/app/profile/pulse-browser.js:51]: **TODO (pulse-browser/website#7):** Web based release notes

**Review by trickypr — APPROVED** [review]
